// src/ai/flows/generate-recipe-audio.ts
'use server';
/**
 * @fileOverview A flow for generating audio narration for a recipe.
 *
 * - generateRecipeAudio - Converts recipe instructions to speech.
 */

import {ai} from '@/ai/genkit';
import wav from 'wav';
import { googleAI } from '@genkit-ai/googleai';
import { GenerateRecipeAudioInput, GenerateRecipeAudioInputSchema, GenerateRecipeAudioOutput, GenerateRecipeAudioOutputSchema } from '../schemas';

async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    const bufs: Buffer[] = [];
    writer.on('error', reject);
    writer.on('data', (d) => bufs.push(d));
    writer.on('end', () => resolve(Buffer.concat(bufs).toString('base64')));

    writer.write(pcmData);
    writer.end();
  });
}

export async function generateRecipeAudio(
  input: GenerateRecipeAudioInput
): Promise<GenerateRecipeAudioOutput> {
  return generateRecipeAudioFlow(input);
}

const generateRecipeAudioFlow = ai.defineFlow(
  {
    name: 'generateRecipeAudioFlow',
    inputSchema: GenerateRecipeAudioInputSchema,
    outputSchema: GenerateRecipeAudioOutputSchema,
  },
  async ({instructions}) => {
    // Add validation to prevent calling the model with an empty string
    if (!instructions || instructions.trim() === '') {
      throw new Error('Cannot generate audio from empty instructions.');
    }
    
    try {
      const { media, finishReason, custom: customResponse } = await ai.generate({
        model: googleAI.model('gemini-2.5-flash-preview-tts'),
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: 'Algenib' },
            },
          },
        },
        prompt: instructions,
      });
      
      // Explicitly check if media is missing, even if finishReason is 'success'
      if (!media) {
        const error = (customResponse as any)?.error;
        let errorMessage = error?.message || 'No media was generated by the AI service.';
        
        console.error('Audio generation failed, no media returned.', {finishReason, error: errorMessage});
        if (errorMessage.includes('429') || errorMessage.toLowerCase().includes('rate limit')) {
             errorMessage = 'Too Many Requests: The free daily quota for audio generation has been exceeded. Please try again later or upgrade your API key.';
        } else if (errorMessage.includes('503')) {
             errorMessage = 'Service Unavailable: The audio generation service is currently overloaded. Please try again in a moment.';
        }
        throw new Error(errorMessage);
      }

      const audioBuffer = Buffer.from(
        media.url.substring(media.url.indexOf(',') + 1),
        'base64'
      );
      
      const wavBase64 = await toWav(audioBuffer);

      return {
        audioDataUri: `data:audio/wav;base64,${wavBase64}`,
      };
    } catch (e: any) {
        // Re-throw specific errors or a generic one
        let displayMessage = e.message || "The AI could not generate audio at this time.";
        if (e.message?.includes('No media was generated')) {
            displayMessage = 'Audio generation failed. This might be due to service limits or a temporary issue. Please try again later.';
        }
        console.error("Audio generation flow error:", e.message);
        throw new Error(displayMessage);
    }
  }
);
